### ISSUE TITLE
The "http://packages.firegento.com/AWeberCommunications_EmailMarketing.json" file could not be downloaded (HTTP/1.1 404 Not Found) 

### ISSUE THREAD

**Issue by mhauri** [magento-hackathon/composer-repository#342]
packages.firegento.com isn't working.

The following error appears after "composer update" is executed.
Even when the Extensions named in the error isn't used.

![bildschirmfoto 2015-11-24 um 09 53 50](https://cloud.githubusercontent.com/assets/402069/11361998/52698c8e-9291-11e5-89b1-aa2dda2429a5.png)

**Comment by gdemad** [comment]
+1

**Comment by kirmorozov** [comment]
same thing https://github.com/Cotya/magento-composer-installer/issues/79

**Comment by daim2k5** [comment]
working on it...

**Comment by craigcarnell** [comment]
Is there any way to skip the errors?

**Comment by azngeek** [comment]
+1

**Comment by azngeek** [comment]
if you need to update the composer.lock file for a specific project, do not run ```composer update vendor/package``` at the moment but directly add your ```composer.lock``` to manually resolve the dependencies. 

Example to update a specific package without ```composer update```. Just update your reference-tag, so that it matches with your desired commit-hash.

```
  "source": {
                "type": "git",
                "url": "ssh://git@repo.mothership.de:8123/ms/component_feed.git",
                "reference": "0373f33981a7c7d58ba43e09e82502f9ce2e0e19"
            }
```

**Comment by ajpevers** [comment]
either it's solved or `composer selfupdate` and `composer update` did the trick

**Comment by thomas-spigel** [comment]
Not working for me...

**Comment by ajpevers** [comment]
Forgot to notice that I also did a `composer clearcache`.

**Comment by thomas-spigel** [comment]
Nope, it's still not working, even with clearcache...

**Comment by kirmorozov** [comment]
Looks like trouble at firegento (Broken repo).
Resolved.

**Comment by thomas-spigel** [comment]
Still getting the same error.
I tried:
 - `composer selfupdate`
 - `composer clearcache`
 - `composer update`
 - `composer install`
 - created new composer file without any packages required
 - removed lock file, tried out.
 - etc.

Still getting it on every server and locally. It didn't work even once for me.

**Comment by azngeek** [comment]
I can confirm that it still does not work here.

**Comment by riconeitzel** [comment]
All you references and links point in a circular relation to this entry here … so … is it closed or is it still open?! :D

**Comment by tniebergall** [comment]
I think it is still open. I get this error a few minutes ago.

**Comment by bjoern-flagbit** [comment]
Still open :-1:

**Comment by riker09** [comment]
Still open

**Comment by samuelecarpene** [comment]
still open

**Comment by craigcarnell** [comment]
Still an issue here

**Comment by halk** [comment]
This error disappeared after clearing caches etc., but now connect20 packages do not work. I guess this is related to @daim2k5's recent commit

**Comment by soplo-o** [comment]
+1

**Comment by bjoern-flagbit** [comment]
We just skip errors now:
```<arg line="satis/bin/satis build --skip-errors satis.json web"/>```

**Comment by daim2k5** [comment]
i need to generate the connect20 packages again, i remove them for the moment. @bjoern-flagbit yes but it doesn't fix the problem ;-)

**Comment by daim2k5** [comment]
But for all of you i make this in my spare time so every

i need this now

or

:-1: 

think about a moment if you all willing to maintain this project for free and for more then 2 weeks.

**Comment by bjoern-flagbit** [comment]
True story ... but when you need to build something ;-) is this a fast solution.

Do we need that required modul? And hey thx for the work :+1:

**Comment by daim2k5** [comment]
Its not only that module i removed more modules but i still get error so i decided for the moment to start the crawler again

**Comment by oleksii-lisovyi** [comment]
Thank you. It's working for now.
Is it the temporary decision?

**Comment by daim2k5** [comment]
I'm working on a solution to bring the connect20 packages back

**Comment by danemacmillan** [comment]
Ah, right, this also affected the connect20 packages. The work is appreciated @daim2k5 !

**Comment by azngeek** [comment]
Thanks for your effort @daim2k5 . I appreciate the good work. I will spend some :beers:  at the next MeetMagento

**Comment by daim2k5** [comment]
Ok we are back in business, connect20 works agains

**Comment by craigcarnell** [comment]
Thank you :+1:
